"""add ondelete to FK constraints

Revision ID: 3e44dad1fba0
Revises: c4d5e6f7a8b9
Create Date: 2026-08-23 13:43:12.246756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e44dad1fba0'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('corrections_entry_id_fkey'), 'corrections', type_='foreignkey')
    op.drop_constraint(op.f('corrections_food_item_id_fkey'), 'corrections', type_='foreignkey')
    op.create_foreign_key(None, 'corrections', 'food_items', ['food_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'corrections', 'log_entries', ['entry_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('food_items_recipe_id_fkey'), 'food_items', type_='foreignkey')
    op.drop_constraint(op.f('food_items_food_id_fkey'), 'food_items', type_='foreignkey')
    op.create_foreign_key(None, 'food_items', 'foods', ['food_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'food_items', 'recipes', ['recipe_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('recipe_ingredients_food_id_fkey'), 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_ingredients', 'foods', ['food_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('recipes_parent_recipe_id_fkey'), 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'recipes', ['parent_recipe_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('targets_derived_from_calibration_id_fkey'), 'targets', type_='foreignkey')
    op.create_foreign_key(None, 'targets', 'calibration_state', ['derived_from_calibration_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'targets', type_='foreignkey')
    op.create_foreign_key(op.f('targets_derived_from_calibration_id_fkey'), 'targets', 'calibration_state', ['derived_from_calibration_id'], ['id'])
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key(op.f('recipes_parent_recipe_id_fkey'), 'recipes', 'recipes', ['parent_recipe_id'], ['id'])
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('recipe_ingredients_food_id_fkey'), 'recipe_ingredients', 'foods', ['food_id'], ['id'])
    op.drop_constraint(None, 'food_items', type_='foreignkey')
    op.drop_constraint(None, 'food_items', type_='foreignkey')
    op.create_foreign_key(op.f('food_items_food_id_fkey'), 'food_items', 'foods', ['food_id'], ['id'])
    op.create_foreign_key(op.f('food_items_recipe_id_fkey'), 'food_items', 'recipes', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'corrections', type_='foreignkey')
    op.drop_constraint(None, 'corrections', type_='foreignkey')
    op.create_foreign_key(op.f('corrections_food_item_id_fkey'), 'corrections', 'food_items', ['food_item_id'], ['id'])
    op.create_foreign_key(op.f('corrections_entry_id_fkey'), 'corrections', 'log_entries', ['entry_id'], ['id'])
    # ### end Alembic commands ###
