"""food_item position, job_runs, unique dinnerware

Revision ID: 88b444f0d07e
Revises: d2cf4afa94f1
Create Date: 2026-08-22 00:47:03.144695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b444f0d07e'
down_revision: Union[str, Sequence[str], None] = 'd2cf4afa94f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job', sa.String(length=100), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job', 'day', name='uq_job_run_day')
    )
    op.create_unique_constraint('uq_dinnerware_user_name', 'dinnerware', ['user_id', 'name'])
    op.add_column('food_items', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'position')
    op.drop_constraint('uq_dinnerware_user_name', 'dinnerware', type_='unique')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
