"""name=remove daily_rollups

Revision ID: cd2e4ddeb178
Revises: c8d3f5a1e07b
Create Date: 2026-08-25 23:42:21.724125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2e4ddeb178'
down_revision: Union[str, Sequence[str], None] = 'c8d3f5a1e07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_rollups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_rollups',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('kcal_reported', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('kcal_calibrated', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('protein_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('carbs_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fat_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('water_ml', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('coverage_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('daily_rollups_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_rollups_pkey')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_rollup_user_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
