"""initial schema

Revision ID: d2cf4afa94f1
Revises: 
Create Date: 2026-08-21 22:22:35.105840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2cf4afa94f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pg_trgm powers Phase 1 name resolution: fuzzy matching on
    # canonical_name_en with an index, no embedding model on the critical path.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # vector is not used yet. Installed now so the Phase 2 columns can be added
    # without touching the extension set on a machine holding real data.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_called_at'), 'api_usage', ['called_at'], unique=False)
    op.create_table('foods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name_en', sa.String(length=200), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('raw', 'boiled', 'grilled', 'fried', 'baked', 'roasted', 'steamed', 'dried', 'liquid', 'unknown', name='food_state'), nullable=False),
    sa.Column('kcal_per_100g', sa.Float(), nullable=False),
    sa.Column('protein_g_per_100g', sa.Float(), nullable=False),
    sa.Column('carbs_g_per_100g', sa.Float(), nullable=False),
    sa.Column('fat_g_per_100g', sa.Float(), nullable=False),
    sa.Column('fiber_g_per_100g', sa.Float(), nullable=True),
    sa.Column('sugar_g_per_100g', sa.Float(), nullable=True),
    sa.Column('sodium_mg_per_100g', sa.Float(), nullable=True),
    sa.Column('density_g_per_ml', sa.Float(), nullable=True),
    sa.Column('yield_factor', sa.Float(), nullable=True),
    sa.Column('fat_absorption_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('turkomp', 'usda_foundation', 'usda_sr', 'usda_branded', 'off', 'label_photo', 'user', 'model', name='food_source'), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=True),
    sa.Column('trust_tier', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('kcal_per_100g >= 0', name='ck_foods_kcal_nonneg'),
    sa.CheckConstraint('trust_tier between 1 and 4', name='ck_foods_trust_tier'),
    sa.CheckConstraint('yield_factor is null or (yield_factor > 0.1 and yield_factor < 5)', name='ck_foods_yield_sane'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name_en', 'state', name='uq_foods_name_state')
    )
    op.create_index('ix_foods_aliases', 'foods', ['aliases'], unique=False, postgresql_using='gin')
    op.create_index('ix_foods_name_trgm', 'foods', ['canonical_name_en'], unique=False, postgresql_using='gin', postgresql_ops={'canonical_name_en': 'gin_trgm_ops'})
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('goal_type', sa.String(length=32), nullable=True),
    sa.Column('goal_rate_kg_per_week', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('calibration_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('k_factor', sa.Float(), nullable=False),
    sa.Column('k_ci_low', sa.Float(), nullable=True),
    sa.Column('k_ci_high', sa.Float(), nullable=True),
    sa.Column('tdee_estimate', sa.Float(), nullable=False),
    sa.Column('tdee_ci_low', sa.Float(), nullable=True),
    sa.Column('tdee_ci_high', sa.Float(), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commitments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('follow_up_result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_rollups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kcal_reported', sa.Float(), nullable=False),
    sa.Column('kcal_calibrated', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('water_ml', sa.Float(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_rollup_user_date')
    )
    op.create_table('dinnerware',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_library',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('times_logged', sa.Integer(), nullable=False),
    sa.Column('last_logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'food_id', name='uq_library_user_food')
    )
    op.create_table('health_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'metric', 'recorded_at', 'source', name='uq_health_natural')
    )
    op.create_index('ix_health_user_metric_time', 'health_metrics', ['user_id', 'metric', 'recorded_at'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('supporting_query', sa.Text(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_reaction', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.Enum('food', 'drink', 'water', 'exercise', 'supplement', 'weight', 'measurement', 'mood', 'satiety', name='entry_kind'), nullable=False),
    sa.Column('source', sa.Enum('photo', 'text', 'voice', 'button', 'library', 'recipe', 'health_sync', 'manual', name='entry_source'), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('raw_input_ref', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by'], ['log_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_entries_user_time', 'log_entries', ['user_id', 'occurred_at'], unique=False)
    op.create_table('portion_priors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('median_grams', sa.Float(), nullable=False),
    sa.Column('p25_grams', sa.Float(), nullable=True),
    sa.Column('p75_grams', sa.Float(), nullable=True),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'food_id', name='uq_prior_user_food')
    )
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_recipe_id', sa.UUID(), nullable=True),
    sa.Column('raw_input_grams', sa.Float(), nullable=True),
    sa.Column('cooked_output_grams', sa.Float(), nullable=True),
    sa.Column('servings', sa.Float(), nullable=True),
    sa.Column('servings_grams', sa.Float(), nullable=True),
    sa.Column('kcal_per_100g', sa.Float(), nullable=True),
    sa.Column('protein_g_per_100g', sa.Float(), nullable=True),
    sa.Column('carbs_g_per_100g', sa.Float(), nullable=True),
    sa.Column('fat_g_per_100g', sa.Float(), nullable=True),
    sa.Column('times_logged', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_weight',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('raw_kg', sa.Float(), nullable=True),
    sa.Column('ewma_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_trend_user_date')
    )
    op.create_table('food_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('detected_name', sa.String(length=200), nullable=True),
    sa.Column('detected_state', sa.Enum('raw', 'boiled', 'grilled', 'fried', 'baked', 'roasted', 'steamed', 'dried', 'liquid', 'unknown', name='food_state'), nullable=True),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('grams_source', sa.Enum('vlm', 'user', 'recipe', 'label', 'library_prior', name='grams_source'), nullable=False),
    sa.Column('grams_confidence', sa.Float(), nullable=True),
    sa.Column('resolution_method', sa.Enum('exact', 'trigram', 'embedding', 'llm_tiebreak', 'recipe', 'library', 'new', name='resolution_method'), nullable=False),
    sa.Column('resolution_confidence', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.CheckConstraint('grams >= 0', name='ck_food_items_grams_nonneg'),
    sa.ForeignKeyConstraint(['entry_id'], ['log_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_entry_id'), 'food_items', ['entry_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['log_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_sha256'), 'media', ['sha256'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('kcal_target', sa.Float(), nullable=False),
    sa.Column('protein_target_g', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('derived_from_calibration_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['derived_from_calibration_id'], ['calibration_state.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('food_item_id', sa.UUID(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applied_to_library', sa.Boolean(), nullable=False),
    sa.Column('applied_to_prior', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['log_entries.id'], ),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perception_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parsed_ok', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['log_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Extensions are deliberately not dropped: another database in the cluster
    # may be using them, and dropping vector would cascade to any column of
    # that type.

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perception_runs')
    op.drop_table('corrections')
    op.drop_table('targets')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_media_sha256'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_food_items_entry_id'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_table('trend_weight')
    op.drop_table('recipes')
    op.drop_table('portion_priors')
    op.drop_index('ix_log_entries_user_time', table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_table('insights')
    op.drop_index('ix_health_user_metric_time', table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_table('food_library')
    op.drop_table('dinnerware')
    op.drop_table('daily_rollups')
    op.drop_table('commitments')
    op.drop_table('calibration_state')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_foods_name_trgm', table_name='foods', postgresql_using='gin', postgresql_ops={'canonical_name_en': 'gin_trgm_ops'})
    op.drop_index('ix_foods_aliases', table_name='foods', postgresql_using='gin')
    op.drop_table('foods')
    op.drop_index(op.f('ix_api_usage_called_at'), table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###

    # Drop enum types after all tables that reference them have been dropped.
    for enum_name in (
        "resolution_method",
        "grams_source",
        "entry_source",
        "entry_kind",
        "food_source",
        "food_state",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
